---
variables: {}

assets: {}

steps:
  init:
    description: "Initialization and Global Context"
  
  extract-source:
    description: "Extract Source Data"
    dependencies: ["init"]

  extract-tokens:
    description: "Extract design tokens from Design Tool and convert to schema format"
    dependencies: ["extract-source"]

  extract-components:
    description: "Extract components from Design Tool and convert to schema format"
    dependencies: ["extract-tokens"]

  extract-stories:
    description: "Extract stories from Design Tool and convert to schema format"
    dependencies: ["extract-components"]

  summary:
    description: "Execution Summary"
    dependencies: ["extract-stories"]
